/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cfg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(_display, _display, AUTO)


PB_BIND(_display_small, _display_small, AUTO)


PB_BIND(_cpu, _cpu, AUTO)


PB_BIND(_cpu_freq, _cpu_freq, AUTO)


PB_BIND(_cpu_core, _cpu_core, AUTO)


PB_BIND(_pen, _pen, 2)


PB_BIND(_pen_show, _pen_show, AUTO)


PB_BIND(_pen_speed, _pen_speed, AUTO)


PB_BIND(_menu, _menu, 2)


PB_BIND(_autosave, _autosave, AUTO)


PB_BIND(_key, _key, AUTO)


PB_BIND(_key_swap, _key_swap, AUTO)


PB_BIND(_joy, _joy, AUTO)


PB_BIND(_joy_lr, _joy_lr, AUTO)


PB_BIND(_joy_lr_xy, _joy_lr_xy, AUTO)


PB_BIND(_joy_lr_remap, _joy_lr_remap, AUTO)


PB_BIND(miyoo_settings, miyoo_settings, 2)









