/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cfg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(_display, _display, AUTO)


PB_BIND(_display__small, _display__small, AUTO)


PB_BIND(_cpu, _cpu, AUTO)


PB_BIND(_cpu__freq, _cpu__freq, AUTO)


PB_BIND(_cpu__core, _cpu__core, AUTO)


PB_BIND(_pen, _pen, 2)


PB_BIND(_pen__speed, _pen__speed, AUTO)


PB_BIND(_menu, _menu, 2)


PB_BIND(_autosave, _autosave, AUTO)


PB_BIND(_keypad, _keypad, AUTO)


PB_BIND(_keypad__swap, _keypad__swap, AUTO)


PB_BIND(_joystick, _joystick, AUTO)


PB_BIND(_joystick__remap, _joystick__remap, AUTO)


PB_BIND(settings, settings, 2)





