/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_CFG_PB_H_INCLUDED
#define PB_CFG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum __keypad__hotkey {
    _keypad__hotkey_menu = 0,
    _keypad__hotkey_select = 1
} _keypad__hotkey;

/* Struct definitions */
typedef struct __display__small {
    int32_t alpha;
    int32_t border;
    int32_t position;
} _display__small;

typedef struct __display {
    int32_t layout;
    int32_t alt_layout;
    _display__small small;
} _display;

typedef struct __cpu__freq {
    int32_t min;
    int32_t max;
} _cpu__freq;

typedef struct __cpu__core {
    int32_t min;
    int32_t max;
} _cpu__core;

typedef struct __cpu {
    _cpu__freq freq;
    _cpu__core core;
} _cpu;

typedef struct __pen__speed {
    int32_t x;
    int32_t y;
} _pen__speed;

typedef struct __pen {
    char image[255];
    bool screen0;
    _pen__speed speed;
} _pen;

typedef struct __menu {
    char bg[255];
    bool show_cursor;
} _menu;

typedef struct __autosave {
    bool enable;
    int32_t slot;
} _autosave;

typedef struct __keypad__swap {
    bool l1_l2;
    bool r1_r2;
} _keypad__swap;

typedef struct __keypad {
    int32_t rotate;
    _keypad__hotkey hotkey;
    _keypad__swap swap;
} _keypad;

typedef struct __joystick__remap {
    int32_t top;
    int32_t down;
    int32_t left;
    int32_t right;
} _joystick__remap;

typedef struct __joystick {
    int32_t mode;
    int32_t dead_zone;
    _joystick__remap remap_left;
    _joystick__remap remap_right;
} _joystick;

typedef struct _settings {
    char version[255];
    char language[255];
    char font_path[255];
    char state_folder[255];
    char border_image[255];
    int32_t system_volume;
    int32_t fast_forward;
    bool half_volume;
    bool low_battery_close;
    _display display;
    _cpu cpu;
    _pen pen;
    _menu menu;
    _autosave autosave;
    _keypad keypad;
    _joystick joystick;
} settings;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define __keypad__hotkey_MIN _keypad__hotkey_menu
#define __keypad__hotkey_MAX _keypad__hotkey_select
#define __keypad__hotkey_ARRAYSIZE ((_keypad__hotkey)(_keypad__hotkey_select+1))










#define _keypad_hotkey_ENUMTYPE _keypad__hotkey






/* Initializer values for message structs */
#define _display_init_default                    {0, 0, _display__small_init_default}
#define _display__small_init_default             {0, 0, 0}
#define _cpu_init_default                        {_cpu__freq_init_default, _cpu__core_init_default}
#define _cpu__freq_init_default                  {0, 0}
#define _cpu__core_init_default                  {0, 0}
#define _pen_init_default                        {"", 0, _pen__speed_init_default}
#define _pen__speed_init_default                 {0, 0}
#define _menu_init_default                       {"", 0}
#define _autosave_init_default                   {0, 0}
#define _keypad_init_default                     {0, __keypad__hotkey_MIN, _keypad__swap_init_default}
#define _keypad__swap_init_default               {0, 0}
#define _joystick_init_default                   {0, 0, _joystick__remap_init_default, _joystick__remap_init_default}
#define _joystick__remap_init_default            {0, 0, 0, 0}
#define settings_init_default                    {"", "", "", "", "", 0, 0, 0, 0, _display_init_default, _cpu_init_default, _pen_init_default, _menu_init_default, _autosave_init_default, _keypad_init_default, _joystick_init_default}
#define _display_init_zero                       {0, 0, _display__small_init_zero}
#define _display__small_init_zero                {0, 0, 0}
#define _cpu_init_zero                           {_cpu__freq_init_zero, _cpu__core_init_zero}
#define _cpu__freq_init_zero                     {0, 0}
#define _cpu__core_init_zero                     {0, 0}
#define _pen_init_zero                           {"", 0, _pen__speed_init_zero}
#define _pen__speed_init_zero                    {0, 0}
#define _menu_init_zero                          {"", 0}
#define _autosave_init_zero                      {0, 0}
#define _keypad_init_zero                        {0, __keypad__hotkey_MIN, _keypad__swap_init_zero}
#define _keypad__swap_init_zero                  {0, 0}
#define _joystick_init_zero                      {0, 0, _joystick__remap_init_zero, _joystick__remap_init_zero}
#define _joystick__remap_init_zero               {0, 0, 0, 0}
#define settings_init_zero                       {"", "", "", "", "", 0, 0, 0, 0, _display_init_zero, _cpu_init_zero, _pen_init_zero, _menu_init_zero, _autosave_init_zero, _keypad_init_zero, _joystick_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define _display__small_alpha_tag                1
#define _display__small_border_tag               2
#define _display__small_position_tag             3
#define _display_layout_tag                      1
#define _display_alt_layout_tag                  2
#define _display_small_tag                       3
#define _cpu__freq_min_tag                       1
#define _cpu__freq_max_tag                       2
#define _cpu__core_min_tag                       1
#define _cpu__core_max_tag                       2
#define _cpu_freq_tag                            1
#define _cpu_core_tag                            2
#define _pen__speed_x_tag                        1
#define _pen__speed_y_tag                        2
#define _pen_image_tag                           1
#define _pen_screen0_tag                         2
#define _pen_speed_tag                           3
#define _menu_bg_tag                             1
#define _menu_show_cursor_tag                    2
#define _autosave_enable_tag                     1
#define _autosave_slot_tag                       2
#define _keypad__swap_l1_l2_tag                  1
#define _keypad__swap_r1_r2_tag                  2
#define _keypad_rotate_tag                       1
#define _keypad_hotkey_tag                       2
#define _keypad_swap_tag                         3
#define _joystick__remap_top_tag                 1
#define _joystick__remap_down_tag                2
#define _joystick__remap_left_tag                3
#define _joystick__remap_right_tag               4
#define _joystick_mode_tag                       1
#define _joystick_dead_zone_tag                  2
#define _joystick_remap_left_tag                 3
#define _joystick_remap_right_tag                4
#define settings_version_tag                     1
#define settings_language_tag                    2
#define settings_font_path_tag                   3
#define settings_state_folder_tag                4
#define settings_border_image_tag                5
#define settings_system_volume_tag               6
#define settings_fast_forward_tag                7
#define settings_half_volume_tag                 8
#define settings_low_battery_close_tag           9
#define settings_display_tag                     10
#define settings_cpu_tag                         11
#define settings_pen_tag                         12
#define settings_menu_tag                        13
#define settings_autosave_tag                    14
#define settings_keypad_tag                      15
#define settings_joystick_tag                    16

/* Struct field encoding specification for nanopb */
#define _display_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    layout,            1) \
X(a, STATIC,   REQUIRED, INT32,    alt_layout,        2) \
X(a, STATIC,   REQUIRED, MESSAGE,  small,             3)
#define _display_CALLBACK NULL
#define _display_DEFAULT NULL
#define _display_small_MSGTYPE _display__small

#define _display__small_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    alpha,             1) \
X(a, STATIC,   REQUIRED, INT32,    border,            2) \
X(a, STATIC,   REQUIRED, INT32,    position,          3)
#define _display__small_CALLBACK NULL
#define _display__small_DEFAULT NULL

#define _cpu_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  freq,              1) \
X(a, STATIC,   REQUIRED, MESSAGE,  core,              2)
#define _cpu_CALLBACK NULL
#define _cpu_DEFAULT NULL
#define _cpu_freq_MSGTYPE _cpu__freq
#define _cpu_core_MSGTYPE _cpu__core

#define _cpu__freq_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    min,               1) \
X(a, STATIC,   REQUIRED, INT32,    max,               2)
#define _cpu__freq_CALLBACK NULL
#define _cpu__freq_DEFAULT NULL

#define _cpu__core_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    min,               1) \
X(a, STATIC,   REQUIRED, INT32,    max,               2)
#define _cpu__core_CALLBACK NULL
#define _cpu__core_DEFAULT NULL

#define _pen_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   image,             1) \
X(a, STATIC,   REQUIRED, BOOL,     screen0,           2) \
X(a, STATIC,   REQUIRED, MESSAGE,  speed,             3)
#define _pen_CALLBACK NULL
#define _pen_DEFAULT NULL
#define _pen_speed_MSGTYPE _pen__speed

#define _pen__speed_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    x,                 1) \
X(a, STATIC,   REQUIRED, INT32,    y,                 2)
#define _pen__speed_CALLBACK NULL
#define _pen__speed_DEFAULT NULL

#define _menu_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   bg,                1) \
X(a, STATIC,   REQUIRED, BOOL,     show_cursor,       2)
#define _menu_CALLBACK NULL
#define _menu_DEFAULT NULL

#define _autosave_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enable,            1) \
X(a, STATIC,   REQUIRED, INT32,    slot,              2)
#define _autosave_CALLBACK NULL
#define _autosave_DEFAULT NULL

#define _keypad_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    rotate,            1) \
X(a, STATIC,   REQUIRED, UENUM,    hotkey,            2) \
X(a, STATIC,   REQUIRED, MESSAGE,  swap,              3)
#define _keypad_CALLBACK NULL
#define _keypad_DEFAULT NULL
#define _keypad_swap_MSGTYPE _keypad__swap

#define _keypad__swap_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     l1_l2,             1) \
X(a, STATIC,   REQUIRED, BOOL,     r1_r2,             2)
#define _keypad__swap_CALLBACK NULL
#define _keypad__swap_DEFAULT NULL

#define _joystick_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    mode,              1) \
X(a, STATIC,   REQUIRED, INT32,    dead_zone,         2) \
X(a, STATIC,   REQUIRED, MESSAGE,  remap_left,        3) \
X(a, STATIC,   REQUIRED, MESSAGE,  remap_right,       4)
#define _joystick_CALLBACK NULL
#define _joystick_DEFAULT NULL
#define _joystick_remap_left_MSGTYPE _joystick__remap
#define _joystick_remap_right_MSGTYPE _joystick__remap

#define _joystick__remap_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    top,               1) \
X(a, STATIC,   REQUIRED, INT32,    down,              2) \
X(a, STATIC,   REQUIRED, INT32,    left,              3) \
X(a, STATIC,   REQUIRED, INT32,    right,             4)
#define _joystick__remap_CALLBACK NULL
#define _joystick__remap_DEFAULT NULL

#define settings_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   version,           1) \
X(a, STATIC,   REQUIRED, STRING,   language,          2) \
X(a, STATIC,   REQUIRED, STRING,   font_path,         3) \
X(a, STATIC,   REQUIRED, STRING,   state_folder,      4) \
X(a, STATIC,   REQUIRED, STRING,   border_image,      5) \
X(a, STATIC,   REQUIRED, INT32,    system_volume,     6) \
X(a, STATIC,   REQUIRED, INT32,    fast_forward,      7) \
X(a, STATIC,   REQUIRED, BOOL,     half_volume,       8) \
X(a, STATIC,   REQUIRED, BOOL,     low_battery_close,   9) \
X(a, STATIC,   REQUIRED, MESSAGE,  display,          10) \
X(a, STATIC,   REQUIRED, MESSAGE,  cpu,              11) \
X(a, STATIC,   REQUIRED, MESSAGE,  pen,              12) \
X(a, STATIC,   REQUIRED, MESSAGE,  menu,             13) \
X(a, STATIC,   REQUIRED, MESSAGE,  autosave,         14) \
X(a, STATIC,   REQUIRED, MESSAGE,  keypad,           15) \
X(a, STATIC,   REQUIRED, MESSAGE,  joystick,         16)
#define settings_CALLBACK NULL
#define settings_DEFAULT NULL
#define settings_display_MSGTYPE _display
#define settings_cpu_MSGTYPE _cpu
#define settings_pen_MSGTYPE _pen
#define settings_menu_MSGTYPE _menu
#define settings_autosave_MSGTYPE _autosave
#define settings_keypad_MSGTYPE _keypad
#define settings_joystick_MSGTYPE _joystick

extern const pb_msgdesc_t _display_msg;
extern const pb_msgdesc_t _display__small_msg;
extern const pb_msgdesc_t _cpu_msg;
extern const pb_msgdesc_t _cpu__freq_msg;
extern const pb_msgdesc_t _cpu__core_msg;
extern const pb_msgdesc_t _pen_msg;
extern const pb_msgdesc_t _pen__speed_msg;
extern const pb_msgdesc_t _menu_msg;
extern const pb_msgdesc_t _autosave_msg;
extern const pb_msgdesc_t _keypad_msg;
extern const pb_msgdesc_t _keypad__swap_msg;
extern const pb_msgdesc_t _joystick_msg;
extern const pb_msgdesc_t _joystick__remap_msg;
extern const pb_msgdesc_t settings_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define _display_fields &_display_msg
#define _display__small_fields &_display__small_msg
#define _cpu_fields &_cpu_msg
#define _cpu__freq_fields &_cpu__freq_msg
#define _cpu__core_fields &_cpu__core_msg
#define _pen_fields &_pen_msg
#define _pen__speed_fields &_pen__speed_msg
#define _menu_fields &_menu_msg
#define _autosave_fields &_autosave_msg
#define _keypad_fields &_keypad_msg
#define _keypad__swap_fields &_keypad__swap_msg
#define _joystick_fields &_joystick_msg
#define _joystick__remap_fields &_joystick__remap_msg
#define settings_fields &settings_msg

/* Maximum encoded size of messages (where known) */
#define CFG_PB_H_MAX_SIZE                        settings_size
#define _autosave_size                           13
#define _cpu__core_size                          22
#define _cpu__freq_size                          22
#define _cpu_size                                48
#define _display__small_size                     33
#define _display_size                            57
#define _joystick__remap_size                    44
#define _joystick_size                           114
#define _keypad__swap_size                       4
#define _keypad_size                             19
#define _menu_size                               259
#define _pen__speed_size                         22
#define _pen_size                                283
#define settings_size                            2121

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
