/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cfg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(_display, _display, AUTO)


PB_BIND(_display__small, _display__small, AUTO)


PB_BIND(_cpu, _cpu, AUTO)


PB_BIND(_cpu__freq, _cpu__freq, AUTO)


PB_BIND(_cpu__core, _cpu__core, AUTO)


PB_BIND(_pen, _pen, 2)


PB_BIND(_pen__show, _pen__show, AUTO)


PB_BIND(_pen__speed, _pen__speed, AUTO)


PB_BIND(_menu, _menu, 2)


PB_BIND(_autosave, _autosave, AUTO)


PB_BIND(_key, _key, AUTO)


PB_BIND(_key__swap, _key__swap, AUTO)


PB_BIND(_joy, _joy, AUTO)


PB_BIND(_joy__lr, _joy__lr, AUTO)


PB_BIND(_joy__lr__xy, _joy__lr__xy, AUTO)


PB_BIND(_joy__lr__remap, _joy__lr__remap, AUTO)


PB_BIND(settings, settings, 2)









